apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-server
  namespace: ark
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30G

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-save
  namespace: ark
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G