apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ark-password
type: Opaque
data:
  server_password: {{ .Values.secret.server_password }}
  admin_password: {{ .Values.secret.admin_password }}