apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.ark_server.name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.ark_server.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.ark_save.name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.ark_save.size }}